### ISSUE TITLE
Downloaded files don't get cleaned up by default

### ISSUE THREAD

**Issue by bear-in-mind** [renuo/so_many_devices#3]
By default, files don't get cleaned up when running tests. Do you think you might :
- Include a way to easily clean up downloads after each tests
- Document it
- Depending on your views about it, maybe make it the default configuration ?
Otherwise, worked straight out after `bundle`, so thanks for that !

**Comment by ghost** [comment]
@coorasse Seems like a reasonable request! Will work on it

**Comment by coorasse** [comment]
I added documentation on how to clean the downloads
